Mosaic/Mosaic.WebUI/Mosaic.WebUI/Controllers/GenerateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Mosaic.WebUI.Models;

namespace Mosaic.WebUI.Controllers
{
    public class GenerateController : Controller
    {
        IMakerClient client = new MakerClient();
        string EDGE_IMAGE_LOCATION = "wwwroot\\images\\edges\\";

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GenerateMosaic(string id, bool random, int tileWidth, int tileHeight, bool colourBlended, bool enhanced, int enhancedThreshold, bool edgeDetection, int edgeDetectionThreshold)
        {
            // Generate the mosaic passing the project id and whether to randomise tile selection
            var model = new GenerateMosaicModel();
            var response = model.Generate(client, id, random, tileWidth, tileHeight, colourBlended, enhanced, enhancedThreshold, edgeDetection, edgeDetectionThreshold);
            if (String.IsNullOrEmpty(response.Error))
            {
                // copy generated image to root directory to allow it display
                var image = new ViewImageModel();
                image.CopyImage(response.Location);
                // update project status and store location
                var insertResponse = new MosaicFileModel().InsertMosaicFile(client, id, image.ImagePath);
                if (String.IsNullOrEmpty(insertResponse.Error))
                {
                    Response.StatusCode = (int)HttpStatusCode.OK;
                    return Json(image.ImagePath);
                }
            }
            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json(response.Error);
        }

        [HttpPost]
        public ActionResult UpdateColourAnalysis(string Id, int height, int width)
        {
            // Generate the mosaic model so enable update to the colour analysis of library
            var model = new GenerateMosaicModel();
            model.ReadProjectData(client, Id, true, height, width);
            if (model.ColoursModel != null)
            {
                Response.StatusCode = (int)HttpStatusCode.OK;
                return Json(model.ColoursModel);
            }
            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json("Error in generating colour model");
        }


        [HttpPost]
        public ActionResult PreviewEdges(string id, int threshold)
        {
            var model = new GenerateMosaicModel();
            var response = model.PreviewEdges(client, id, threshold);
            if (String.IsNullOrEmpty(response.Error))
            {
                // copy generated image to root directory to allow it display
                var image = new ViewImageModel(EDGE_IMAGE_LOCATION);
                image.CopyImage(response.Location);
                // update project status and store location
                var insertResponse = new EdgeFileModel().InsertEdgeFile(client, id, image.ImagePath);
                if (String.IsNullOrEmpty(insertResponse.Error))
                {
                    Response.StatusCode = (int)HttpStatusCode.OK;
                    return Json(image.ImagePath);
                }
            }
            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json(response.Error);
        }
    }
}

Mosaic/Mosaic.WebUI/Mosaic.WebUI/Controllers/MasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Infrastructure;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Mosaic.WebUI.Models;

namespace Mosaic.WebUI.Controllers
{
    public class MasterController : Controller
    {
        IMakerClient client = new MakerClient();
        string MASTER_IMAGE_LOCATION = "wwwroot\\images\\master\\";

        [HttpPost]
        public ActionResult ReadImageFileIndex(string indexedLocation, string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Project id cannot be null or empty");
            }
            var model = new ImageFileIndexModel();
            model.ReadImageFileIndexMaster(client, indexedLocation);

            if (String.IsNullOrEmpty(model.Error))
            {
                Response.StatusCode = (int)HttpStatusCode.OK;
                return Json(model.Files);
            }

            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json(model.Error);
        }

        [HttpPost]
        public ActionResult ImportMaster(string id, string fileId, string filePath)
        {
            // copy master image to root directory to allow it display
            // set the name of the local master image to the project id
            var image = new ViewImageModel(MASTER_IMAGE_LOCATION);
            image.CopyImage(filePath, id);

            // update project status and store master file id
            var model = new MasterFileModel();
            var response = model.InsertMasterFile(client, id, fileId, image.ImagePath);
            if (String.IsNullOrEmpty(response.Error))
            {
                Response.StatusCode = (int)HttpStatusCode.OK;
                return Json("The update large file id request was valid");
            }
            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json(response.Error);
        }

        [HttpPost]
        public ActionResult ViewImage(string filepath, string id)
        {
            var model = new ViewImageModel(MASTER_IMAGE_LOCATION);
            model.CopyImage(filepath, id);
            if (String.IsNullOrEmpty(model.Error))
            {
                Response.StatusCode = (int)HttpStatusCode.OK;
                return Json(model.FilePath);
            }
            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json(model.Error);
        }

        public ActionResult ImportTiles(string Id)
        {
            // pass client into constructor
            var model = new IndexedLocationModel(client, Id);
            model.RequestIndexedLocation(client);

            return View("ImportTiles", model);
        }
    }
}

Mosaic/Mosaic.WebUI/Mosaic.WebUI/Controllers/TileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Mosaic.WebUI.Models;

namespace Mosaic.WebUI.Controllers
{
    public class TileController : Controller
    {
        IMakerClient client = new MakerClient();

        [HttpPost]
        public ActionResult UpdateIndexedLocation(string indexedLocation, string id)
        {
            // pass client into constructor
            var model = new IndexedLocationModel(client, id);

            var response = model.UpdateIndexedLocation(client, indexedLocation);
            if (String.IsNullOrEmpty(response.Error))
            {
                Response.StatusCode = (int)HttpStatusCode.OK;
                return Json("The indexed location request was valid");
            }
            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json(response.Error);
        }

        [HttpPost]
        public ActionResult ReadImageFileIndex(string indexedLocation, string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Project id cannot be null or empty");
            }
            var model = new ImageFileIndexModel();
            model.ReadImageFileIndex(client, indexedLocation, id);

            if (String.IsNullOrEmpty(model.Error))
            {
                var tileTableModel = model.Files.Select(x => new TileTableModel(x));
                Response.StatusCode = (int)HttpStatusCode.OK;
                return Json(tileTableModel);
            }

            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json(model.Error);
        }

        [HttpPost]
        public ActionResult UpdateImageFileIndex(string indexedLocation)
        {
            var model = new ImageFileIndexModel();

            var response = model.UpdateImageFileIndex(client, indexedLocation);
            if (String.IsNullOrEmpty(response.Result.Error))
            {
                Response.StatusCode = (int)HttpStatusCode.OK;
                return Json("The update image file index request was valid");
            }
            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json(response.Result.Error);
        }

        [HttpPost]
        [RequestFormSizeLimit(valueCountLimit: 2000)]
        public ActionResult ImportTiles(string id, IEnumerable<string> fileIds)
        {
            var model = new TileFilesModel();

            var response = model.InsertSmallFiles(client, id, fileIds.ToList());
            if (String.IsNullOrEmpty(response.Error))
            {
                Response.StatusCode = (int)HttpStatusCode.OK;
                return Json("The update small file ids request was valid");
            }
            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json(response.Error);
        }

        public ActionResult Generate(string Id)
        {
            var model = new GenerateMosaicModel();
            model.ReadProjectData(client, Id);

            return View("Generate", model);
        }
    }
}

Mosaic/Mosaic.WebUI/Mosaic.WebUI/Views/Shared/ImportMaster.cshtml
@model Mosaic.WebUI.Models.IndexedLocationModel

@{
    ViewData["Title"] = "ImportMaster";
}

@Html.Partial("_ProjectNavBar", Model.PartialModel)

<div class="jumbotron jumbotron-with-navbar">
    <h1 class="display-4">Select Master File</h1>
    <hr class="my-4">
    <p>Select master file from local system directory to use in the creation of the mosaic image.</p>
</div>


<nav class="navbar bg-faded">
    <form class="form-inline">
        @Html.EditorFor(x=> x.IndexedLocation,
            new { htmlAttributes = new { @class = "form-control mr-sm-2", style = "Width:400px" } })
        <button id="update_indexed_location" class="btn btn-outline-success my-2 my-sm-0" type="button">Update</button>
    </form>
</nav>

@*<img src="~/images/face_image.jpg" class="rounded mx-auto d-block master-image" alt="~/images/face_image.jpg">*@

<table id="example" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>FileName</th>
            <th>FilePath</th>
            <th>Metadata</th>
            <th>Last Write Time</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>ID</th>
            <th>FileName</th>
            <th>FilePath</th>
            <th>Metadata</th>
            <th>Last Write Time</th>
        </tr>
    </tfoot>
</table>

<form class="form-inline">
    <button id="import_files" class="btn btn-outline-success my-2 my-sm-0 pull-right" disabled type="button">Import</button>
</form>

<script src="~/lib/jquery/dist/jquery.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="~/lib/DataTables/datatables.css">
<script src="~/lib/DataTables/datatables.js" type="text/javascript" charset="utf8"></script>

<script>

    $(function () {
        $.noConflict();
        var table = $('#example').DataTable({
            select: true,
            "columnDefs": [
                { "visible": false, "targets": 0 },
                { "visible": false, "targets": 3 }
            ]
        });

        var importBtn = document.getElementById('import_files');

        $('#example tbody').on('click', 'tr', function () {
            if ($(this).hasClass('selected')) {
                $(this).removeClass('selected');
                $(importBtn).attr("disabled", true);
            }
            else {
                table.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');
                $(importBtn).attr("disabled", false);
            }
        });

        // To Do
        // On change index location, pass the following three ajax calls
        // in a method which will perform all three in turn
        // In this method will also perform the javascript to indicate the
        // indexing is occuring
        var updateIndexedLocation = function (IndexedLocation) {

            $.ajax({
                type: "POST",
                url: '@Url.Action("UpdateIndexedLocation", "Tile")',
                dataType: 'json',
                cache: false,
                data: { IndexedLocation: IndexedLocation, Id: "@Model.ProjectId" },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Invalid request");
                    // Display a toastr message to indicate failure
                },
                success: function () {
                    // Once implemented this will call the function to update the file list
                    updateImageFileIndex(IndexedLocation);
                }
            });
        }

        var updateImageFileIndex = function (IndexedLocation) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("UpdateImageFileIndex", "Tile")',
                dataType: 'json',
                cache: false,
                data: { IndexedLocation: IndexedLocation },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Invalid request");
                    // Display a toastr message to indicate failure
                },
                success: function () {
                    // Once implemented this will call the function to update the file list
                    readImageFileIndex(IndexedLocation);
                }
            });
        }

        var readImageFileIndex = function (IndexedLocation) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("ReadImageFileIndex", "Master")',
                dataType: 'json',
                cache: false,
                data: { IndexedLocation: IndexedLocation, Id : "@Model.ProjectId" },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Invalid request");
                    // Display a toastr message to indicate failure
                },
                success: function (response) {
                    // Once implemented this will call the function to update the file list
                    populateTable(response);
                }
            });
        }

        var populateTable = function (data) {
            table.clear();
            table.destroy();

            table = $('#example').DataTable({
                "data" : data,
                "columns": [
                    { "data": "id" },
                    { "data": "fileName" },
                    { "data": "filePath" },
                    { "data": "data" },
                    { "data": "lastWriteTime" }
                ],
                "columnDefs": [
                    { "visible": false, "targets": 0 },
                    { "visible": false, "targets": 3 }
                ]
            });
        }

        var importMaster = function (id, fileId, filePath) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("ImportMaster", "Master")',
                dataType: 'json',
                traditional: true,
                cache: false,
                data: { id: id, fileId: fileId, filePath: filePath },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Invalid request");
                },
                success: function (response) {
                    window.location.href = '@Url.Action("ImportTiles", "Master", new { Id = Model.ProjectId })';
                }
            });
        }

        // Need to block extra request whilst indexing operation ongoing
        $("#update_indexed_location").click(function () {
            var data = $("#IndexedLocation").val();
            updateIndexedLocation(data);
        });

        var location = $("#IndexedLocation").val()
        updateImageFileIndex(location);

        $("#import_files").click(function () {
            var data = table.rows('.selected').data();
            importMaster("@Model.ProjectId", data[0].id, data[0].filePath);
        });
    });
</script>


Mosaic/Mosaic.WebUI/Mosaic.WebUI/Views/Shared/ImportTiles.cshtml
@model Mosaic.WebUI.Models.IndexedLocationModel

@{
    ViewData["Title"] = "Indexed Tile Files";
}
@Html.Partial("_ProjectNavBar", Model.PartialModel)

<div class="jumbotron jumbotron-with-navbar">
    <h1 class="display-4">Select Tile Files</h1>
    <hr class="my-4">
    <p>Select files from local system directory to use in the creation of the mosaic image.</p>
</div>


<nav class="navbar bg-faded">
    <form class="form-inline">
        @Html.EditorFor(x=> x.IndexedLocation,
            new { htmlAttributes = new { @class = "form-control mr-sm-2", style = "Width:400px" } })
        <button id="update_indexed_location" class="btn btn-outline-success my-2 my-sm-0" type="button">Update</button>
    </form>
</nav>

<table id="example" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>FileName</th>
            <th>FilePath</th>
            <th>Average Colour</th>
            <th>Standard Colour</th>
            <th>Last Write Time</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>ID</th>
            <th>FileName</th>
            <th>FilePath</th>
            <th>Standard Colour</th>
            <th>Last Write Time</th>
        </tr>
    </tfoot>
</table>

<form class="form-inline">
    <button id="import_files" class="btn btn-outline-success my-2 my-sm-0 pull-right" disabled type="button">Import</button>
</form>

<script src="~/lib/jquery/dist/jquery.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="~/lib/DataTables/datatables.css">
<script src="~/lib/DataTables/datatables.js" type="text/javascript" charset="utf8"></script>

<script>
    $(function () {
        $.noConflict();
        var table = $('#example').DataTable({
            select: true,
            dom: 'Blfrtip',
            "columnDefs": [
                { "visible": false, "targets": 0 }
            ],
            buttons: [
                'selectAll',
                'selectNone'
            ]
        });

        var importBtn = document.getElementById('import_files');

        $('#example tbody').on('click', 'tr', function () {
            $(this).toggleClass('selected');
            if (table.rows('.selected').data().length == 0) {
                $(importBtn).attr("disabled", true);
            }
            else {
                $(importBtn).attr("disabled", false);
            }
        });

        table.on('buttons-action', function() {
            if (table.rows('.selected').data().length == 0) {
                $(importBtn).attr("disabled", true);
            }
            else {
                $(importBtn).attr("disabled", false);
            }
        });

        var updateIndexedLocation = function (IndexedLocation) {

            $.ajax({
                type: "POST",
                url: '@Url.Action("UpdateIndexedLocation", "Tile")',
                dataType: 'json',
                cache: false,
                data: { IndexedLocation: IndexedLocation, Id: "@Model.ProjectId" },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Invalid request");
                    // Display a toastr message to indicate failure
                },
                success: function () {
                    // Once implemented this will call the function to update the file list
                    updateImageFileIndex(IndexedLocation);
                }
            });
        }


        var updateImageFileIndex = function (IndexedLocation) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("UpdateImageFileIndex", "Tile")',
                dataType: 'json',
                cache: false,
                data: { IndexedLocation: IndexedLocation },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Invalid request");
                    // Display a toastr message to indicate failure
                },
                success: function () {
                    // Once implemented this will call the function to update the file list
                    readImageFileIndex(IndexedLocation);
                }
            });
        }

        var readImageFileIndex = function (IndexedLocation) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("ReadImageFileIndex", "Tile")',
                dataType: 'json',
                cache: false,
                data: { IndexedLocation: IndexedLocation, Id : "@Model.ProjectId" },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Invalid request");
                    // Display a toastr message to indicate failure
                },
                success: function (response) {
                    // Once implemented this will call the function to update the file list
                    populateTable(response);
                }
            });
        }

        var populateTable = function (data) {

            table.clear();
            table.destroy();

            table = $('#example').DataTable({
                "data": data,
                dom: 'Blfrtip',
                "columns": [
                    { "data": "id" },
                    { "data": "fileName" },
                    { "data": "filePath" },
                    { "data": "averageColour" },
                    { "data": "standardColour" },
                    { "data": "lastWriteTime" }
                ],
                "columnDefs": [
                    { "visible": false, "targets": 0 }
                ],
                buttons: [
                    {
                        extend: 'selectAll',
                        className: 'selectall',
                        action: function (e) {
                            e.preventDefault();
                            table.rows({ search: 'applied' }).deselect();
                            table.rows({ search: 'applied' }).select();
                        }
                    },
                    'selectNone'
                ],
                "createdRow": function (row, data, index) {
                    $('td', row).eq(2).css('background-color', data.averageColour);
                    $('td', row).eq(3).css('background-color', data.standardColour);
                }
            });
        }

        var importTiles = function (id, fileIds) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("ImportTiles", "Tile")',
                dataType: 'json',
                traditional: true,
                cache: false,
                data: { id: id, fileIds: fileIds },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Invalid request");
                },
                success: function (response) {
                    window.location.href = '@Url.Action("Generate","Tile", new { Id = Model.ProjectId })';
                }
            });
        }

        // Need to block extra request whilst indexing operation ongoing
        $("#update_indexed_location").click(function () {
            var data = $("#IndexedLocation").val();
            updateIndexedLocation(data);
        });

        var location = $("#IndexedLocation").val()
        updateImageFileIndex(location);

        $("#import_files").click(function () {
            var data = table.rows('.selected').data();
            var fileIds = $.map(data, function (n) {
                return n.id;
            });
            importTiles("@Model.ProjectId", fileIds);
        });
    });
</script>

Mosaic/Mosaic.WebUI/Mosaic.WebUI/Views/Shared/_ImageCarousel.cshtml

@{
    ViewData["Title"] = "_ImageCarousel";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/face_image.jpg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <button type="button" class="btn btn-primary create_mosaic">
                    Create my Mosaic
                </button>
                <p>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/seagull_image.jpg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <button type="button" class="btn btn-primary create_mosaic">
                    Create my Mosaic
                </button>
                <p>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/face_image_2.jpg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <button type="button" class="btn btn-primary create_mosaic">
                    Create my Mosaic
                </button>
                <p>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<script src="~/lib/jquery/dist/jquery.js" type="text/javascript"></script>
<script>
    $(function () {

        var createMosaic = function () {
            $.ajax({
                type: "POST",
                url: '@Url.Action("Create", "Home")',
                dataType: 'json',
                cache: false,
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Invalid request");
                },
                success: function (response) {
                    var id = response.project.id;
                    var link = '@Url.Action("ImportMaster", "Home", new { Id = "-1" })';
                    link = link.replace("-1", id);
                    window.location.href = link;

                }
            });
        }

        $(".create_mosaic").click(function () {
            createMosaic();
        });
    });
</script>


Mosaic/Mosaic.WebUI/Mosaic.WebUI/Views/Shared/_ProjectNavBar.cshtml
@model Tuple<string, ProjectStructure.Types.State>
@{
    ViewData["Title"] = "_ProjectNavBar";
}

<nav id="subnav" class="navbar navbar-default navbar-light navbar-centred" role="navigation">

        <div class="navbar-collapse collapse">

            <ul class="nav navbar-nav">
                <li><a id="masterLink" asp-area="" asp-controller="Home" asp-action="ImportMaster" asp-route-Id="@Model.Item1">Master</a></li>
                <li><a id="tilesLink" asp-area="" asp-controller="Master" asp-action="ImportTiles" asp-route-Id="@Model.Item1">Tiles</a></li>
                <li><a id="generateLink" asp-area="" asp-controller="Tile" asp-action="Generate" asp-route-Id="@Model.Item1">Generate</a></li>
            </ul>
        </div>
</nav>

<script src="~/lib/jquery/dist/jquery.js" type="text/javascript"></script>
<script>
    $(function () {
        var tiles = document.getElementById("tilesLink");
        var generate = document.getElementById("generateLink");
        var created = "@ProjectStructure.Types.State.Created";
        var largeAdded = "@ProjectStructure.Types.State.Largeadded";
        
        var state = "@Model.Item2";
        if (state == created) {
            $(tiles).addClass("disabled");
            $(tiles).removeAttr("href");
            $(generate).addClass("disabled");
            $(generate).removeAttr("href");
        }
        else if (state == largeAdded) {
            $(generate).addClass("disabled");
            $(generate).removeAttr("href");
        }
    });
</script>

Mosaic/Mosaic.WebUI/Mosaic.WebUI/Views/Shared/_TileImage.cshtml

@{
    ViewData["Title"] = "_TileImage";
}

<html>
<body>
    <div class="media">
        <canvas id="canvas"></canvas>
        <script type="text/javascript" src="~/js/GridImage.js"></script>
    </div>
</body>
</html>
